<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <RootNamespace>Reservoir.TestSupport</RootNamespace>
    <AssemblyName>Reservoir.TestSupport</AssemblyName>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="RabbitMQ.Client" Version="6.8.1" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Reservoir.BuildingBlocks\Reservoir.BuildingBlocks.csproj" />
  </ItemGroup>

</Project>
